# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pete88b.github.io/clinical_trial_eligibility/"

git_url = "https://github.com/pete88b/clinical_trial_eligibility/tree/main/"

def custom_doc_links(name): return None
